### PR TITLE
Fix for an InvalidCastException and an invalid item/vehicle id NRE error in the shop command.

### PR DESCRIPTION
**Pull request by cartman-2000**
Trying to use the UnturnedPlayer type cast on caller will give an InvalidCastException error when the command is ran from the console.

Also a check has been added that checks for a valid item or vehicle id when entered into the shop command.

Second commit is for this issue #5 .

### CODE REVIEW

**Comment by Zamirathe** [comment]
Did you check this?  I saw you changed all playerid to caller.  So why make the change to playerid then?

**Comment by cartman-2000** [comment]
Yes, I've tested the changes and it all works. It's a bit unnecessary to convert IRocketPlayer to UnturnedPlayer for the UnturnedChat.Say lines of code as .Say handles IRocketPlayer natively, It's really only needed for the .IsAdmin piece of code in the shop command. 

The only thing in that command that was necessary for it to work was the if statement for the cast, and the valid asset check. It would have been necessary for the other changed lines of message code only if UnturnedChat.Say was used directly, instead of through the sendMessage function, as putting a null for the caller in .Say will get a NRE error. I could undo the changes to all of the sendMessage lines and the sendMessage function, if you want.

You get this error in the if the shop command was run in the console with the cast. This cast error is something that I've encountered when updating my plugins to 4.6.

```
[7/29/2015 3:03:52 PM] [Error] An error occured while executing command /shop : System.InvalidCastException: Cannot cast from source type to destination type.
  at ZaupShop.CommandShop.Execute (IRocketPlayer caller, System.String[] msg) [0x00000] in <filename unknown>:0 
  at Rocket.Unturned.Commands.UnturnedCommandBase.executeCommand (IRocketCommand command, CSteamID caller, System.String commandString) [0x00000] in <filename unknown>:0 
```

The second commit is for this Issue #5.

**Comment by cartman-2000** [comment]
The .IsAdmin check can be further simplified.

**Comment by lightphoenix2** [comment]
Im also getting the same error if I run the commands from console in my own plugins after I update it to 4.6

**Comment by lightphoenix2** [comment]
All I know is 
UnturnedPlayer player = (UnturnedPlayer)caller
Is the cause of the error as it fail to convert IRocketPlayer to UnturnedPlayer

**Comment by lightphoenix2** [comment]
This Works though:

```
public void Execute(IRocketPlayer caller, string[] msg)
        {
            bool console = (caller is ConsolePlayer);
            bool[] perms = { false, false, false, false, false };
            bool anyuse = false;
            string message;
            foreach (string s in Permissions)
            {
                switch (s)
                {
                    case "shop.*":
                        perms[0] = true;
                        anyuse = true;
                        break;
                    case "shop.add":
                        perms[1] = true;
                        anyuse = true;
                        break;
                    case "shop.rem":
                        perms[2] = true;
                        anyuse = true;
                        break;
                    case "shop.chng":
                        perms[3] = true;
                        anyuse = true;
                        break;
                    case "shop.buy":
                        perms[4] = true;
                        anyuse = true;
                        break;
                    case "*":
                        perms[0] = true;
                        perms[1] = true;
                        perms[2] = true;
                        perms[3] = true;
                        perms[4] = true;
                        anyuse = true;
                        break;
                }
            }
            if (console)
            {
                perms[0] = true;
                perms[1] = true;
                perms[2] = true;
                perms[3] = true;
                perms[4] = true;
                anyuse = true;
            }
            if (!anyuse && !console)
            {
                // Assume this is a player
                UnturnedChat.Say(caller, "You don't have permission to use the /shop command.");
                return;
            }
```

**Comment by cartman-2000** [comment]
Actually for that the foreach line "foreach (string s in Permissions)" would need to be "foreach (string s in caller.GetPermissions())" for it to work properly with the perms the player has, and if you had that then you wouldn't need the "if (console)" block of code, as using the GetPermissions on a console player sends back a "*" perm which would match what's in the foreach block. But also for that, you would need to have the correct group perms for a player to use the shop command, as having Unturned(Builtin) admin wouldn't give them permission to use the command, without a .IsAdmin check.

**Comment by lightphoenix2** [comment]
```
        public void Execute(IRocketPlayer caller, string[] msg)
        {
            bool console = (caller is ConsolePlayer);
            bool[] perms = { false, false, false, false, false };
            bool anyuse = false;
            string message;
            foreach (string s in caller.GetPermissions())
            {
                switch (s)
                {
                    case "shop.*":
                        perms[0] = true;
                        anyuse = true;
                        break;
                    case "shop.add":
                        perms[1] = true;
                        anyuse = true;
                        break;
                    case "shop.rem":
                        perms[2] = true;
                        anyuse = true;
                        break;
                    case "shop.chng":
                        perms[3] = true;
                        anyuse = true;
                        break;
                    case "shop.buy":
                        perms[4] = true;
                        anyuse = true;
                        break;
                    case "*":
                        perms[0] = true;
                        perms[1] = true;
                        perms[2] = true;
                        perms[3] = true;
                        perms[4] = true;
                        anyuse = true;
                        break;
                }
            }
            if (!anyuse && !console)
            {
                // Assume this is a player
                UnturnedChat.Say(caller, "You don't have permission to use the /shop command.");
                return;
            }
```

**Pull request merged**
